name: ptyhon app tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    strategy:
      matrix:
        ptyhon-version: [3.8, 3.9, 3.11]

    env:
      MODE: "dev"

    steps:
      - uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Intall dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: test app code
        run: python ./main.py
